Listen 18083

<VirtualHost *:18083>
    ServerName 51.68.175.222

    ProxyPreserveHost On
    ProxyRequests Off

    RequestHeader set X-Forwarded-Proto "http"

    <Location />
        AuthType Basic
        AuthName "Ticketing DuckDB UI"
        AuthUserFile /etc/apache2/.htpasswd-ticketing-duckdb
        Require valid-user
    </Location>

    ProxyPass        / http://127.0.0.1:14213/
    ProxyPassReverse / http://127.0.0.1:14213/

    ErrorLog ${APACHE_LOG_DIR}/ticketing-duckdb-ui-error.log
    CustomLog ${APACHE_LOG_DIR}/ticketing-duckdb-ui-access.log combined
</VirtualHost>
