Listen 18083

<VirtualHost *:18083>
    ServerName 51-68-175-222.sslip.io

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/51-68-175-222.sslip.io/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/51-68-175-222.sslip.io/privkey.pem

    ProxyPreserveHost On
    ProxyRequests Off

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "18083"
    Header always set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
    Header always set Pragma "no-cache"
    Header always set Expires "0"

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://127.0.0.1:14213/$1 [P,L]

    ProxyPass        / http://127.0.0.1:14213/
    ProxyPassReverse / http://127.0.0.1:14213/

    ErrorLog ${APACHE_LOG_DIR}/ticketing-duckdb-ui-error.log
    CustomLog ${APACHE_LOG_DIR}/ticketing-duckdb-ui-access.log combined
</VirtualHost>
