services:
  web:
    environment:
      VITE_SUPABASE_URL: http://localhost:54321
      VITE_SUPABASE_PUBLISHABLE_KEY: ${ANON_KEY:-replace_me}
      VITE_ANALYTICS_API_URL: http://localhost:8000
    ports: !override
      - "8081:8080"
    volumes: !override []
